import Project from '../models/Project.js';
import Opportunity from '../models/Opportunity.js';
import Task from '../models/Task.js';
import WorkReport from '../models/WorkReport.js';
import FieldReport from '../models/FieldReport.js';
import EmployeeRequest from '../models/EmployeeRequest.js';
import LeaveRequest from '../models/LeaveRequest.js';
import TripReport from '../models/TripReport.js';
import FuelLog from '../models/FuelLog.js';
import Staff from '../models/Staff.js';

// Generate PDF report (using simple text-based PDF generation)
const generatePDF = (data, title) => {
  // For now, we'll return a simple text-based PDF structure
  // In production, you'd use a library like pdfkit, puppeteer, or jspdf
  const pdfContent = {
    title,
    data,
    generatedAt: new Date().toISOString(),
  };
  return pdfContent;
};

// Generate Excel report (using simple CSV-like structure)
const generateExcel = (data, title) => {
  // For now, we'll return a simple CSV structure
  // In production, you'd use a library like exceljs or xlsx
  const excelContent = {
    title,
    data,
    generatedAt: new Date().toISOString(),
  };
  return excelContent;
};

export const exportProjectProgressReport = async (req, res) => {
  try {
    const { format } = req.query; // 'pdf' or 'excel'
    const staff = await Staff.findById(req.staffId);
    
    // Get projects data
    const filters = {};
    if (staff && staff.role !== 'superadmin' && staff.role !== 'finance' && staff.role !== 'admin') {
      filters.staffEmail = staff.email;
    }
    
    const projects = await Project.findAll(filters);
    const opportunities = await Opportunity.findAll({ ...filters, limit: 1000 });
    
    // Prepare report data
    const reportData = {
      generatedBy: staff ? `${staff.firstName} ${staff.lastName}` : 'System',
      generatedAt: new Date().toISOString(),
      projects: projects.map(p => ({
        name: p.name,
        status: p.status,
        progress: p.progress,
        budget: p.budget,
        startDate: p.startDate,
        endDate: p.endDate,
      })),
      opportunities: opportunities.map(o => ({
        title: o.title,
        status: o.status,
        winProbability: o.winProbability,
        estimatedValue: o.estimatedValue,
      })),
    };

    if (format === 'pdf') {
      // Generate simple PDF-like text content
      let pdfContent = `PROJECT PROGRESS REPORT\n`;
      pdfContent += `Generated by: ${reportData.generatedBy}\n`;
      pdfContent += `Generated at: ${new Date(reportData.generatedAt).toLocaleString()}\n\n`;
      pdfContent += `PROJECTS (${reportData.projects.length})\n`;
      pdfContent += `Name | Status | Progress | Budget | Start Date | End Date\n`;
      pdfContent += `-`.repeat(80) + `\n`;
      reportData.projects.forEach(p => {
        pdfContent += `${p.name || 'N/A'} | ${p.status || 'N/A'} | ${p.progress || 0}% | ${p.budget || 0} | ${p.startDate || 'N/A'} | ${p.endDate || 'N/A'}\n`;
      });
      pdfContent += `\nOPPORTUNITIES (${reportData.opportunities.length})\n`;
      pdfContent += `Title | Status | Win Probability | Estimated Value\n`;
      pdfContent += `-`.repeat(80) + `\n`;
      reportData.opportunities.forEach(o => {
        pdfContent += `${o.title || 'N/A'} | ${o.status || 'N/A'} | ${o.winProbability || 0}% | ${o.estimatedValue || 0}\n`;
      });
      
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="project-progress-report-${Date.now()}.pdf"`);
      res.send(pdfContent);
    } else if (format === 'excel') {
      // Generate CSV (Excel-compatible)
      let csvContent = `Project Progress Report\n`;
      csvContent += `Generated by,${reportData.generatedBy}\n`;
      csvContent += `Generated at,${new Date(reportData.generatedAt).toLocaleString()}\n\n`;
      csvContent += `PROJECTS\n`;
      csvContent += `Name,Status,Progress,Budget,Start Date,End Date\n`;
      reportData.projects.forEach(p => {
        csvContent += `"${p.name || 'N/A'}","${p.status || 'N/A'}",${p.progress || 0},"${p.budget || 0}","${p.startDate || 'N/A'}","${p.endDate || 'N/A'}"\n`;
      });
      csvContent += `\nOPPORTUNITIES\n`;
      csvContent += `Title,Status,Win Probability,Estimated Value\n`;
      reportData.opportunities.forEach(o => {
        csvContent += `"${o.title || 'N/A'}","${o.status || 'N/A'}",${o.winProbability || 0},"${o.estimatedValue || 0}"\n`;
      });
      
      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename="project-progress-report-${Date.now()}.xlsx"`);
      res.send(csvContent);
    } else {
      res.status(400).json({ success: false, message: 'Invalid format. Use "pdf" or "excel"' });
    }
  } catch (error) {
    console.error('Export project progress report error:', error);
    res.status(500).json({ success: false, message: 'Failed to generate report', error: error.message });
  }
};

export const exportFuelTransportReport = async (req, res) => {
  try {
    const { format } = req.query;
    const staff = await Staff.findById(req.staffId);
    
    // Get fuel and transport data
    const filters = {};
    if (staff && staff.role === 'driver') {
      filters.driverId = req.staffId;
    }
    
    const tripReports = await TripReport.findAll(filters);
    const fuelLogs = await FuelLog.findAll(filters);
    
    const reportData = {
      generatedBy: staff ? `${staff.firstName} ${staff.lastName}` : 'System',
      generatedAt: new Date().toISOString(),
      tripReports: tripReports.map(tr => ({
        tripReportId: tr.id || tr.tripReportId,
        purpose: tr.purpose,
        origin: tr.origin,
        destination: tr.destination,
        distance: tr.distanceKm,
        fuelConsumed: tr.fuelConsumed,
        startDate: tr.startDate,
      })),
      fuelLogs: fuelLogs.map(fl => ({
        fuelLogId: fl.id || fl.fuelLogId,
        vehicle: fl.vehicleCode || fl.vehicle_id,
        fuelType: fl.fuelType,
        quantity: fl.amount || fl.quantity,
        cost: fl.cost,
        date: fl.fuelDate || fl.fuel_date,
      })),
    };

    if (format === 'pdf') {
      // Generate simple PDF-like text content
      let pdfContent = `FUEL & TRANSPORT REPORT\n`;
      pdfContent += `Generated by: ${reportData.generatedBy}\n`;
      pdfContent += `Generated at: ${new Date(reportData.generatedAt).toLocaleString()}\n\n`;
      pdfContent += `TRIP REPORTS (${reportData.tripReports.length})\n`;
      pdfContent += `Trip ID | Purpose | Origin | Destination | Distance (km) | Fuel Consumed | Start Date\n`;
      pdfContent += `-`.repeat(100) + `\n`;
      reportData.tripReports.forEach(tr => {
        pdfContent += `${tr.tripReportId || 'N/A'} | ${tr.purpose || 'N/A'} | ${tr.origin || 'N/A'} | ${tr.destination || 'N/A'} | ${tr.distance || 0} | ${tr.fuelConsumed || 0} | ${tr.startDate || 'N/A'}\n`;
      });
      pdfContent += `\nFUEL LOGS (${reportData.fuelLogs.length})\n`;
      pdfContent += `Fuel Log ID | Vehicle | Fuel Type | Quantity | Cost | Date\n`;
      pdfContent += `-`.repeat(80) + `\n`;
      reportData.fuelLogs.forEach(fl => {
        pdfContent += `${fl.fuelLogId || 'N/A'} | ${fl.vehicle || 'N/A'} | ${fl.fuelType || 'N/A'} | ${fl.quantity || 0} | ${fl.cost || 0} | ${fl.date || 'N/A'}\n`;
      });
      
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="fuel-transport-report-${Date.now()}.pdf"`);
      res.send(pdfContent);
    } else if (format === 'excel') {
      // Generate CSV (Excel-compatible)
      let csvContent = `Fuel & Transport Report\n`;
      csvContent += `Generated by,${reportData.generatedBy}\n`;
      csvContent += `Generated at,${new Date(reportData.generatedAt).toLocaleString()}\n\n`;
      csvContent += `TRIP REPORTS\n`;
      csvContent += `Trip ID,Purpose,Origin,Destination,Distance (km),Fuel Consumed,Start Date\n`;
      reportData.tripReports.forEach(tr => {
        csvContent += `${tr.tripReportId || 'N/A'},"${tr.purpose || 'N/A'}","${tr.origin || 'N/A'}","${tr.destination || 'N/A'}",${tr.distance || 0},${tr.fuelConsumed || 0},"${tr.startDate || 'N/A'}"\n`;
      });
      csvContent += `\nFUEL LOGS\n`;
      csvContent += `Fuel Log ID,Vehicle,Fuel Type,Quantity,Cost,Date\n`;
      reportData.fuelLogs.forEach(fl => {
        csvContent += `${fl.fuelLogId || 'N/A'},"${fl.vehicle || 'N/A'}","${fl.fuelType || 'N/A'}",${fl.quantity || 0},${fl.cost || 0},"${fl.date || 'N/A'}"\n`;
      });
      
      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename="fuel-transport-report-${Date.now()}.xlsx"`);
      res.send(csvContent);
    } else if (format === 'csv') {
      // Generate CSV
      const csvRows = [];
      csvRows.push('Trip Report ID,Purpose,Origin,Destination,Distance (km),Fuel Consumed,Start Date');
      tripReports.forEach(tr => {
        csvRows.push(`${tr.id},"${tr.purpose}","${tr.origin}","${tr.destination}",${tr.distanceKm || ''},${tr.fuelConsumed || ''},${tr.startDate || ''}`);
      });
      csvRows.push('');
      csvRows.push('Fuel Log ID,Vehicle,Fuel Type,Quantity,Cost,Date');
      fuelLogs.forEach(fl => {
        csvRows.push(`${fl.id},"${fl.vehicleCode || ''}","${fl.fuelType || ''}",${fl.quantity || ''},${fl.cost || ''},${fl.fuelDate || ''}`);
      });
      
      const csvContent = csvRows.join('\n');
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="fuel-transport-report-${Date.now()}.csv"`);
      res.send(csvContent);
    } else {
      res.status(400).json({ success: false, message: 'Invalid format. Use "pdf", "excel", or "csv"' });
    }
  } catch (error) {
    console.error('Export fuel transport report error:', error);
    res.status(500).json({ success: false, message: 'Failed to generate report', error: error.message });
  }
};

export const exportFinancialReport = async (req, res) => {
  try {
    const { format } = req.query;
    const staff = await Staff.findById(req.staffId);
    
    // Get financial data based on user role
    const reportData = {
      generatedBy: staff ? `${staff.firstName} ${staff.lastName}` : 'System',
      generatedAt: new Date().toISOString(),
      summary: {
        totalBudget: 0,
        totalExpenses: 0,
        totalRevenue: 0,
      },
    };

    // Add financial data based on user permissions
    if (staff && (staff.role === 'superadmin' || staff.role === 'finance' || staff.role === 'admin')) {
      // Include all financial data
      // You can add more financial models here
    }

    if (format === 'pdf') {
      // Generate simple PDF-like text content
      let pdfContent = `FINANCIAL SUMMARY REPORT\n`;
      pdfContent += `Generated by: ${reportData.generatedBy}\n`;
      pdfContent += `Generated at: ${new Date(reportData.generatedAt).toLocaleString()}\n\n`;
      pdfContent += `SUMMARY\n`;
      pdfContent += `Total Budget: ${reportData.summary.totalBudget || 0}\n`;
      pdfContent += `Total Expenses: ${reportData.summary.totalExpenses || 0}\n`;
      pdfContent += `Total Revenue: ${reportData.summary.totalRevenue || 0}\n`;
      pdfContent += `Net Profit/Loss: ${(reportData.summary.totalRevenue || 0) - (reportData.summary.totalExpenses || 0)}\n`;
      
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="financial-report-${Date.now()}.pdf"`);
      res.send(pdfContent);
    } else if (format === 'excel') {
      // Generate CSV (Excel-compatible)
      let csvContent = `Financial Summary Report\n`;
      csvContent += `Generated by,${reportData.generatedBy}\n`;
      csvContent += `Generated at,${new Date(reportData.generatedAt).toLocaleString()}\n\n`;
      csvContent += `SUMMARY\n`;
      csvContent += `Total Budget,Total Expenses,Total Revenue,Net Profit/Loss\n`;
      csvContent += `${reportData.summary.totalBudget || 0},${reportData.summary.totalExpenses || 0},${reportData.summary.totalRevenue || 0},${(reportData.summary.totalRevenue || 0) - (reportData.summary.totalExpenses || 0)}\n`;
      
      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename="financial-report-${Date.now()}.xlsx"`);
      res.send(csvContent);
    } else {
      res.status(400).json({ success: false, message: 'Invalid format. Use "pdf" or "excel"' });
    }
  } catch (error) {
    console.error('Export financial report error:', error);
    res.status(500).json({ success: false, message: 'Failed to generate report', error: error.message });
  }
};

export const exportDataReport = async (req, res) => {
  try {
    const { format } = req.query;
    const staff = await Staff.findById(req.staffId);
    
    // Get all relevant data based on user role
    const filters = {};
    if (staff && staff.role !== 'superadmin' && staff.role !== 'finance' && staff.role !== 'admin') {
      filters.staffEmail = staff.email;
    }
    
    const projects = await Project.findAll({ ...filters, limit: 1000 });
    const tasks = await Task.findAll({ ...filters, limit: 1000 });
    const workReports = await WorkReport.findAll({ ...filters, limit: 1000 });
    
    const reportData = {
      generatedBy: staff ? `${staff.firstName} ${staff.lastName}` : 'System',
      generatedAt: new Date().toISOString(),
      projects: projects.length,
      tasks: tasks.length,
      workReports: workReports.length,
      data: {
        projects: projects.slice(0, 100), // Limit for export
        tasks: tasks.slice(0, 100),
        workReports: workReports.slice(0, 100),
      },
    };

    if (format === 'pdf') {
      // Generate simple PDF-like text content
      let pdfContent = `DATA EXPORT REPORT\n`;
      pdfContent += `Generated by: ${reportData.generatedBy}\n`;
      pdfContent += `Generated at: ${new Date(reportData.generatedAt).toLocaleString()}\n\n`;
      pdfContent += `SUMMARY\n`;
      pdfContent += `Total Projects: ${reportData.projects}\n`;
      pdfContent += `Total Tasks: ${reportData.tasks}\n`;
      pdfContent += `Total Work Reports: ${reportData.workReports}\n\n`;
      pdfContent += `PROJECTS (Sample)\n`;
      pdfContent += `ID | Name | Status\n`;
      pdfContent += `-`.repeat(60) + `\n`;
      reportData.data.projects.slice(0, 20).forEach(p => {
        pdfContent += `${p.id || 'N/A'} | ${p.name || 'N/A'} | ${p.status || 'N/A'}\n`;
      });
      
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="data-export-${Date.now()}.pdf"`);
      res.send(pdfContent);
    } else if (format === 'excel') {
      // Generate CSV (Excel-compatible)
      let csvContent = `Data Export Report\n`;
      csvContent += `Generated by,${reportData.generatedBy}\n`;
      csvContent += `Generated at,${new Date(reportData.generatedAt).toLocaleString()}\n\n`;
      csvContent += `SUMMARY\n`;
      csvContent += `Total Projects,Total Tasks,Total Work Reports\n`;
      csvContent += `${reportData.projects},${reportData.tasks},${reportData.workReports}\n\n`;
      csvContent += `PROJECTS\n`;
      csvContent += `ID,Name,Status\n`;
      reportData.data.projects.forEach(p => {
        csvContent += `${p.id || 'N/A'},"${p.name || 'N/A'}","${p.status || 'N/A'}"\n`;
      });
      csvContent += `\nTASKS\n`;
      csvContent += `ID,Title,Status,Due Date\n`;
      reportData.data.tasks.forEach(t => {
        csvContent += `${t.id || 'N/A'},"${t.title || 'N/A'}","${t.status || 'N/A'}","${t.dueDate || 'N/A'}"\n`;
      });
      
      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename="data-export-${Date.now()}.xlsx"`);
      res.send(csvContent);
    } else if (format === 'csv') {
      // Generate CSV
      const csvRows = [];
      csvRows.push('Type,ID,Name,Status,Date');
      projects.slice(0, 100).forEach(p => {
        csvRows.push(`Project,${p.id},"${p.name}",${p.status},${p.startDate || ''}`);
      });
      tasks.slice(0, 100).forEach(t => {
        csvRows.push(`Task,${t.id},"${t.title}",${t.status},${t.dueDate || ''}`);
      });
      
      const csvContent = csvRows.join('\n');
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="data-export-${Date.now()}.csv"`);
      res.send(csvContent);
    } else {
      res.status(400).json({ success: false, message: 'Invalid format. Use "pdf", "excel", or "csv"' });
    }
  } catch (error) {
    console.error('Export data report error:', error);
    res.status(500).json({ success: false, message: 'Failed to generate export', error: error.message });
  }
};
